name: LightsOut
description: "2 as well as 3 states lights out combined"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equations: ^5.0.2
  cupertino_icons: ^1.0.6
  fraction: ^5.0.2
  dart_numerics: ^0.0.6
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  get: ^4.6.6
  pinput: ^4.0.0
  intl_phone_number_input: ^0.7.4
  audioplayers: ^6.0.0
  cloud_firestore: ^4.16.1
  intl: ^0.19.0
  settings_ui: ^2.0.2
  double_back_to_close_app: ^2.1.0
  modal_progress_hud_alt: ^1.0.0
  url_launcher: ^6.2.6
  page_flip_builder: ^0.1.4
  fluttertoast: ^8.2.5
  motion_toast: ^2.9.1
  google_sign_in: ^6.2.1
  loading_overlay_pro: ^2.1.1
  lottie: ^3.1.0
  animated_splash_screen: ^1.3.0
  flutter_facebook_auth: ^6.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/five.png
    - assets/four.png
    - assets/three.png
    - assets/two.png
    - assets/otp.png
    - assets/background_image.jpg
    - assets/background_image_two.jpg
    - assets/google.png
    - assets/tap.mp3
    - assets/weak.mp3
    - assets/success.mp3
    - assets/profiledefault.png
    - assets/animations/
    - assets/

  fonts:
    - family: Game
      fonts:
        - asset: fonts/Game-Regular.otf
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf

